# Site settings
title: "MegaEinfa.ch"
email: "kontakt@thepoweraddicts.com"
description: "PowerPlatform erklärt - Experten im Flow, live, interaktiv, praxisnah"
baseurl: "/MegaEinfa.ch" # the subpath of your site, e.g. /blog
url: "https://marcelehmann.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:categories/:year/:month/:day/:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Collections
collections:
  recordings:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "recordings"
    values:
      layout: "recording"

# Tag-System für Recordings
tag_colors:
  "Power Apps": "#6b46c1"
  "Power Automate": "#059669"
  "Power BI": "#dc2626"
  "Copilot Studio": "#2563eb"
  "Governance": "#7c3aed"
  "ALM": "#ea580c"
  "AI": "#f59e0b"
  "Dataverse": "#10b981"
  "Fabric": "#8b5cf6"
  "Grundlagen": "#6b7280"
  "Advanced": "#ef4444"
